/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/patient-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clinician)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clinician)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clinician)'}/recommendations` | `/recommendations`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clinician)'}/xai` | `/xai`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/data` | `/data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/recommendations` | `/recommendations`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/risk` | `/risk`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/xai` | `/xai`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/patient-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clinician)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clinician)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clinician)'}/recommendations` | `/recommendations`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clinician)'}/xai` | `/xai`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/data` | `/data`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/recommendations` | `/recommendations`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/risk` | `/risk`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/xai` | `/xai`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/patient-detail${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(clinician)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(clinician)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(clinician)'}/recommendations${`?${string}` | `#${string}` | ''}` | `/recommendations${`?${string}` | `#${string}` | ''}` | `${'/(clinician)'}/xai${`?${string}` | `#${string}` | ''}` | `/xai${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/data${`?${string}` | `#${string}` | ''}` | `/data${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/recommendations${`?${string}` | `#${string}` | ''}` | `/recommendations${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/risk${`?${string}` | `#${string}` | ''}` | `/risk${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/xai${`?${string}` | `#${string}` | ''}` | `/xai${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/patient-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clinician)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clinician)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clinician)'}/recommendations` | `/recommendations`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clinician)'}/xai` | `/xai`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/data` | `/data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/recommendations` | `/recommendations`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/risk` | `/risk`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/xai` | `/xai`; params?: Router.UnknownInputParams; };
    }
  }
}
