"""audit chain unique constraints

Revision ID: 8e901cc3bbbc
Revises: 5d2d8c797582
Create Date: 2026-05-31 20:40:19.619076
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e901cc3bbbc'
down_revision: Union[str, None] = '5d2d8c797582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_entry_hash'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_entry_hash'), 'audit_logs', ['entry_hash'], unique=True)
    op.drop_index(op.f('ix_audit_logs_sequence'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_sequence'), 'audit_logs', ['sequence'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_sequence'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_sequence'), 'audit_logs', ['sequence'], unique=False)
    op.drop_index(op.f('ix_audit_logs_entry_hash'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_entry_hash'), 'audit_logs', ['entry_hash'], unique=False)
    # ### end Alembic commands ###
