// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logo-variants/A_Precision.tsx": () => import("../components/mockups/logo-variants/A_Precision.tsx"),
  "./components/mockups/logo-variants/B_MedicalPro.tsx": () => import("../components/mockups/logo-variants/B_MedicalPro.tsx"),
  "./components/mockups/logo-variants/C_UltraMinimal.tsx": () => import("../components/mockups/logo-variants/C_UltraMinimal.tsx"),
  "./components/mockups/logo-variants/LogoV1.tsx": () => import("../components/mockups/logo-variants/LogoV1.tsx"),
  "./components/mockups/logo-variants/LogoV2.tsx": () => import("../components/mockups/logo-variants/LogoV2.tsx"),
  "./components/mockups/logo-variants/NewLogo.tsx": () => import("../components/mockups/logo-variants/NewLogo.tsx"),
  "./components/mockups/dashboard/ClinicDashA.tsx": () => import("../components/mockups/dashboard/ClinicDashA.tsx"),
  "./components/mockups/dashboard/ClinicDashA1.tsx": () => import("../components/mockups/dashboard/ClinicDashA1.tsx"),
  "./components/mockups/dashboard/ClinicDashA2.tsx": () => import("../components/mockups/dashboard/ClinicDashA2.tsx"),
  "./components/mockups/dashboard/ClinicDashB.tsx": () => import("../components/mockups/dashboard/ClinicDashB.tsx"),
  "./components/mockups/dashboard/U1Hierarchy.tsx": () => import("../components/mockups/dashboard/U1Hierarchy.tsx"),
  "./components/mockups/dashboard/U2Affordance.tsx": () => import("../components/mockups/dashboard/U2Affordance.tsx"),
  "./components/mockups/dashboard/U3Access.tsx": () => import("../components/mockups/dashboard/U3Access.tsx"),
  "./components/mockups/dashboard/V3Dark.tsx": () => import("../components/mockups/dashboard/V3Dark.tsx"),
  "./components/mockups/dashboard/V3Vivid.tsx": () => import("../components/mockups/dashboard/V3Vivid.tsx"),
  "./components/mockups/dashboard/XaiV1.tsx": () => import("../components/mockups/dashboard/XaiV1.tsx"),
  "./components/mockups/dashboard/XaiV2.tsx": () => import("../components/mockups/dashboard/XaiV2.tsx"),
  "./components/mockups/dashboard/XaiV3.tsx": () => import("../components/mockups/dashboard/XaiV3.tsx")
};
