// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/ClinicDashA.tsx": () => import("../components/mockups/dashboard/ClinicDashA.tsx"),
  "./components/mockups/dashboard/ClinicDashA1.tsx": () => import("../components/mockups/dashboard/ClinicDashA1.tsx"),
  "./components/mockups/dashboard/ClinicDashA2.tsx": () => import("../components/mockups/dashboard/ClinicDashA2.tsx"),
  "./components/mockups/dashboard/ClinicDashB.tsx": () => import("../components/mockups/dashboard/ClinicDashB.tsx"),
  "./components/mockups/dashboard/XaiV1.tsx": () => import("../components/mockups/dashboard/XaiV1.tsx"),
  "./components/mockups/dashboard/XaiV2.tsx": () => import("../components/mockups/dashboard/XaiV2.tsx"),
  "./components/mockups/dashboard/XaiV3.tsx": () => import("../components/mockups/dashboard/XaiV3.tsx"),
  "./components/mockups/logo-variants/A_Precision.tsx": () => import("../components/mockups/logo-variants/A_Precision.tsx"),
  "./components/mockups/logo-variants/B_MedicalPro.tsx": () => import("../components/mockups/logo-variants/B_MedicalPro.tsx"),
  "./components/mockups/logo-variants/C_UltraMinimal.tsx": () => import("../components/mockups/logo-variants/C_UltraMinimal.tsx"),
  "./components/mockups/logo-variants/LogoV1.tsx": () => import("../components/mockups/logo-variants/LogoV1.tsx"),
  "./components/mockups/logo-variants/LogoV2.tsx": () => import("../components/mockups/logo-variants/LogoV2.tsx"),
  "./components/mockups/logo-variants/NewLogo.tsx": () => import("../components/mockups/logo-variants/NewLogo.tsx")
};
